### ISSUE TITLE
Post without file & ID removal for capcode

### ISSUE THREAD

**Issue by mjthompson** [MitsubaBBS/Mitsuba#20]
2 small ideas for you.

I've shonkly implemented both into my own.
1. Allow mod+ to post without a file.
2. Remove ID's from capcoded users.

**Comment by Desuneko** [comment]
I added support for op posts without files, so I'll do the "No file" option soon.

Also, I've applied your patch.

Thank you.

**Comment by Desuneko** [comment]
Okay, "no file" done
