### ISSUE TITLE
Board links

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#24]
Board links are broken, and whenever you try to rebuild them you get this error:

Fatal error: Call to undefined method Cacher::rebuildBoardLinks() in /home/websitename/public_html/inc/mod/cache.inc.php on line 10

**Comment by Desuneko** [comment]
Fixed in https://github.com/MitsubaBBS/Mitsuba/commit/a3fb600141c5bb9a3fb78af4da50fbf8da8eb70c

**Comment by Desuneko** [comment]
Also, I'm going to make some changes in board links code.
