### ISSUE TITLE
Board links still not working

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#26]
Rebuilding the board links cache works now, but when I try to add a child to a category some error flashes before I can read it, and no board link is created.

**Comment by Desuneko** [comment]
Fixed in https://github.com/MitsubaBBS/Mitsuba/commit/00e4d117ca531f299639e21c1dc370a427cc6595

Sorry for so many errors, but I'm planning to rewrite the code for board links.
