### ISSUE TITLE
Boards completely broken.

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#28]
They look like absolute sh*t. Here's a screencap of a brand new installation of mitsuba on a local server.
![screenshot_1](https://f.cloud.github.com/assets/4838691/733883/b14f0eb4-e2ac-11e2-87d5-d01136e10e3f.png)

**Comment by Desuneko** [comment]
Fixed in https://github.com/MitsubaBBS/Mitsuba/commit/3df042502e6b09984081a55ace4f5fef08a9d292

You'll have to reinstall the script.
