### ISSUE TITLE
Not exactly an issue, but I didn't know where to put this.

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#30]
I rearranged the 4chan style homepage thing so that in my opinion looks better, and adds the news box onto it. Here's a picture of what it looks like, just tell me if you'd like to see my code adjustments.
![screenshot_3](https://f.cloud.github.com/assets/4838691/747745/f5589844-e470-11e2-9314-4dadd70f3ac7.png)

**Comment by Desuneko** [comment]
Thank you for your interest in project. You can publish your code on Gist and I'll include it when I'll do the "templates" thingy.

**Comment by infamousbutterly** [comment]
Alrighty. Let me just figure out how to do that...

**Comment by infamousbutterly** [comment]
https://gist.github.com/infamousbutterly/5929398

**Comment by Desuneko** [comment]
Thank you.

**Comment by Desuneko** [comment]
How you would like to have your frontpage style called?

**Comment by infamousbutterly** [comment]
Oh sweet man! Can you call it Aevus?

**Comment by infamousbutterly** [comment]
Actually, instead call it butter.

**Comment by Desuneko** [comment]
Okay, I'll add it after I'll fix all the issues with other ones.

**Comment by infamousbutterly** [comment]
Yeah, no hurry. I've just been doing it myself anyway, so it doesn't matter. Actually, I just realized I should figure out how to make a pull request and just do it for you.
