### ISSUE TITLE
Top board links don't work.

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#33]
![screenshot_7](https://f.cloud.github.com/assets/4838691/752075/9ad4b424-e52f-11e2-97c9-171159e32e9c.png)
These ones.

**Comment by infamousbutterly** [comment]
They do this thing where it goes to the board, but within the previous board
![screenshot_8](https://f.cloud.github.com/assets/4838691/752077/bc46366e-e52f-11e2-9104-a629fb58a795.png)

**Comment by infamousbutterly** [comment]
![screenshot_9](https://f.cloud.github.com/assets/4838691/752079/c9a1cce2-e52f-11e2-8bb3-743dcf1715fb.png)

**Comment by Desuneko** [comment]
Have you configured them like this (I plan to fix them and link them to boards soon):

url - ../e/
url_index - ./e/
url_thread - ../../e/

**Comment by Desuneko** [comment]
Fixed in https://github.com/MitsubaBBS/Mitsuba/commit/5206546eb863b15b8337c66f02ea1de075b65fec

You'll have to reinstall Mitsuba because of database changes.
