### ISSUE TITLE
Backlinks completely broken.

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#34]
This is what happens when you try and quote a post.
![screenshot_11](https://f.cloud.github.com/assets/4838691/754200/1fa2e814-e581-11e2-903e-d0b6dad4617a.png)

**Comment by Desuneko** [comment]
Fixed in https://github.com/MitsubaBBS/Mitsuba/commit/467f1117961b49cb412b0386a585e9ac8d76e6da
