### ISSUE TITLE
Meny problems

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#35]
Meny is too close to the [return] button, so whenever you try to click on it, it opens up meny and you can't do so. Not a huge issue, but meny is annoying with this being so.

**Comment by Desuneko** [comment]
We are working on it.

**Comment by infamousbutterly** [comment]
They are pretty much fixed on the desktop, but on mobile or touchscreen devices it's still pretty glitchy.

**Comment by Desuneko** [comment]
Fixed.
