### ISSUE TITLE
Configuration glitch.

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#36]
Unsure if this is intentional or not, but I decided I might as well at least make you aware .
![screenshot_5](https://f.cloud.github.com/assets/4838691/777836/c95f93b4-e9a2-11e2-99dd-d0ecfb0fe415.png)

**Comment by Desuneko** [comment]
Yeah, I know about this. I'm not going to fix it until I'll finish all the planned things.

**Comment by infamousbutterly** [comment]
Ok, we'll it's pretty unimportant, so that's fine.
