### ISSUE TITLE
Mod posting

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#45]
when you post as a mod/ admin, you get a CAN'T BOARD error.

**Comment by Desuneko** [comment]
Yeah, it's fixed, I'll push the changes after I'll do the Mysterious Board Update.

**Comment by infamousbutterly** [comment]
Ok, sounds good. I just want to say, I really do like your software. I've been comparing yours to tinyboard, and as far as content goes, yours is much better. They are pretty good as far as bug fixing goes, but overall, you have a good thing going and I prefer it to tinyboard and all other imageboard software. I guess what to take out of this, is good job. You've earned a pat on the back at the very least. Plus, you don't take 3 weeks to patch a bug. Keep up the good work man.

**Comment by Desuneko** [comment]
Thanks for your opinion.

Also, fixed in https://github.com/MitsubaBBS/Mitsuba/commit/f2f9e1308b0374e19cd81e05614d7fcd2f71be6e
