### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#48]
Not an issue, but are there any pointers that you could give me on how to make it so that all of the files have no extension? I don't mean like mod_rewrite, I want to make it so that the files themselves are extension-less. Obviously I've messed around with caching.php, but I just fuck things up. Any help would be much appreciated.

**Comment by Desuneko** [comment]
You can only use mod_rewrite or write a imageboard in node.js. Then remove .html from caching.php

**Comment by infamousbutterly** [comment]
Unsure what you mean with the node.js thing. I'll explore caching.php a bit more.

**Comment by infamousbutterly** [comment]
Aha, I figured it out. Thanks.
