### ISSUE TITLE
BAD PASSWORD OR USERNAME

### ISSUE THREAD

**Issue by infamousbutterly** [MitsubaBBS/Mitsuba#57]
Get this error whenever you try to log in. I tried fixing it, but to no avail.

**Comment by Desuneko** [comment]
I know about this one, it's problem with install.php.

Use: `UPDATE users SET password=SHA2("root", 512), salt="";` And you should able to log into your user with password `root`

**Comment by Desuneko** [comment]
Aaaaand... fixed.
