### ISSUE TITLE
Mitsuba license changes

### ISSUE THREAD

**Issue by Desuneko** [MitsubaBBS/Mitsuba#60]
Well, I'll have to add `By uploading patches you are giving up your rights to those patches` or stuff in case someone wants to sue us and I need the agreement of almost all the people involved in Mitsuba.

Just write that you agree or not and your suggestions about this.

**Comment by infamousbutterly** [comment]
I agree.

**Comment by skandaI** [comment]
I agree.

**Comment by czaks** [comment]
Lol dicks are really good and I like sucking them, please fill me with your cum. Btw. I'm a huge faggot.

**I LIKE SUCKING COCKS**

**Comment by czaks** [comment]
I can't stand that someone has made better script than me so I need to act like I'm better than everyone. btw, trix, i lov u. i wanna suck your cock XDDD

also, i agree.

**Comment by ghost** [comment]
LOL. Łabanowski, what's wrong with you? XDDD Do you even lift? XDDD

**Comment by ghost** [comment]
then i agree too XDDD

**Comment by czaks** [comment]
Oh you kids, get a life

**(USER WAS BANNED FOR THIS POST)**
