### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by balthasar02** [MitsubaBBS/Mitsuba#61]
Hi, I tried Mitsuba, I'm not sure of what happened but I'd like to report it, after using install.php there was an error "There was an error when creating your account!" it's strange, this is not the first time I install an imageboard, and the database is okay, thoughts?

**Comment by infamousbutterly** [comment]
Is the database empy? Could you give any specifications I what type of server you're running? What was the other imageboard software you installed?

**Comment by balthasar02** [comment]
Hi, yes, the database, I created it just to try this out, well, I started again, I filled the info correctly again, this time, a messege said the account was created successfully, then it redirects me to the /mod.php I had the most wonderful smile, but then, these messeges appear:

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/a4820557/public_html/inc/mitsuba.php on line 22

Parse error: syntax error, unexpected T_STRING in /home/a4820557/public_html/inc/mitsuba.php on line 22
__
What could it be? Line 22 is:
        $this->bans = new \Mitsuba\Admin\Bans($this->conn, $this->mitsuba);

Well, I installed  Futallaby some time ago, back then I recall I had to edit the config.php, I'm using 
Apache ver. 2.2.19 (Unix) 
PHP version 5.2.*
MySQL ver.  5.1
a free hosting(as I said I'm just testing)

Thanks for the advice, I really want to run this, I honestly didn't like futallaby.

**Comment by infamousbutterly** [comment]
If you're using a free host you'll almost always have problems. If you'd just like to test it out, I'd recommend setting up a local server so that you can configure it correctly. If you plan on running a website then you absolutely want to invest in paid hosting. That being said, it is a possibility that it's a mitsuba issue. I'm not the main developer of this script, but I'm sure desuneko will be around tomorrow to help you further. Something that you could try doing is asking if your host will upgrade your php version to 5.4, as this often fixes problems for me.

**Comment by balthasar02** [comment]
I understand, I'll try doing that tomorrow, I will post here the results, thank you very much for your time.

**Comment by balthasar02** [comment]
Hi, this is different, I upgraded to 5.4 and tried Mitsuba again, filled the install.php fields, it said the Account was created successfully, then I tried to go to Admin panel, it redirects me to install.php again. I'll keep trying.

No script errors this time. I still have the other site with the free account just in case something solves that, but this event I think shows that the outdated 5.2 php could be ONE of the reasons.

**Comment by Desuneko** [comment]
The new problem is because of chmods, you should change the root directory chmod to 777, also you should change the ./styles chmod to 755.

BTW. I'm working on a better installer that will detect all problems.

**Comment by balthasar02** [comment]
AAAAH damn nevermind I know right that was stupid, it worked thanks, this looks awesome, great job guys!

**Comment by Desuneko** [comment]
So I'll close the issue, if you have any more problems or you want to update Mitsuba on your production server/imageboard, I can prepare the update.sql file for you (you'll have to provide me with copy of your current database.sql file (NOT THE DUMP OF DATABASE, database.sql from Mitsuba)).
