### ISSUE TITLE
Rebuild static pages, Insufficient permisions

### ISSUE THREAD

**Issue by RikkaTakanashi** [MitsubaBBS/Mitsuba#62]
I try 755 all folders and files, but same error all time, i am logged on administrator

**Comment by Desuneko** [comment]
I know where the problem is. I'll fix it.

**Comment by Desuneko** [comment]
https://github.com/MitsubaBBS/Mitsuba/commit/8cce629d7608d94c34e2fe80034eaae93ffbaf70
