### ISSUE TITLE
API doesn't work in barbakan.gov

### ISSUE THREAD

**Issue by ghost** [MitsubaBBS/Mitsuba#76]
![capture](https://cloud.githubusercontent.com/assets/3106216/3178124/fd5f7e6e-ec16-11e3-8401-feab19ee01b4.PNG)
I'm fellow-developer of kuragen-premium and I'm disapointed by kuragen which is missing this interesting feature, can I ask you when i would be glad to see this running?

**Comment by skandaI** [comment]
Developer nie żyje od miesięcy.

**Comment by ghost** [comment]
nie da sie tego przypadkiem w kucmałpie wykucować?

**Comment by skandaI** [comment]
Raczej nie wiesz o czym mówisz.

**Comment by ghost** [comment]
chodzi o to ze to api by ulatwilo kucowanie w kucmalpie

**Comment by ghost** [comment]
ehh jesteś anonem masz przejebane

**Comment by skandaI** [comment]
Właściwie to mogę włączyć spod panelu "Enable API", aczkolwiek nie mam pojęcia, czy to działa. xD

**Comment by ghost** [comment]
testowałbym

**Comment by skandaI** [comment]
Włączyłem. Sprawdź, czy jest jakaś różnica.

**Comment by ghost** [comment]
co ten github taki odnosnikowy

**Comment by ghost** [comment]
http://karachan.org/b/res/6976618.json

**Comment by skandaI** [comment]
Updater postów jest i być może wymaga tylko drobnej naprawy w common.js

**Comment by ghost** [comment]
pokazuje, teraz tylko sprawdzicz czy legitnie

**Comment by skandaI** [comment]
Dużo to pomoże, jeśli działa?

**Comment by ghost** [comment]
raczej pomoże czy dużo to nie wiem,
miło by było jakbyś zostawił włączone na dłużej xD

**Comment by ghost** [comment]
no ale na innych deskach to ty włącz

**Comment by skandaI** [comment]
Już. Musiałem odbudować kesza.

**Comment by ghost** [comment]
<3
