### ISSUE TITLE
API is sending deleted threads

### ISSUE THREAD

**Issue by ghost** [MitsubaBBS/Mitsuba#78]
reproduction for cockroach.gov:
http://karachan.org/b/res/7229452.json
http://karachan.org/b/res/7229452.html

**Comment by skandaI** [comment]
Może dlatego, że posty po usunięciu są jeszcze przez jakiś czas przetrzymywane w bazie do wglądu? Sprawdzałeś na starszych fredach?

**Comment by ghost** [comment]
Niet i nie mam żadnego linka do starszej

**Comment by ghost** [comment]
btw wytestował 10 id koło geta 7000000 a tam jakiś nowy fred musiał być 
i zawsze było 404 
also śmiechłbym jakby kurabin czymał posty od tak długiego czasu

**Comment by pavulon** [comment]
Nie było usuwania JSON-ów przy kasowaniu spadających fredów.

> also śmiechłbym jakby kurabin czymał posty od tak długiego czasu

aż tak źle nie było, jedyne 30 tysięcy plików xD

**Comment by ghost** [comment]
Grzebaliście coś przy tym?

**Comment by ghost** [comment]
Biega dobrze dzienki
