### ISSUE TITLE
Random polish bible quotes

### ISSUE THREAD

**Issue by TheAdamGalloway** [MitsubaBBS/Mitsuba#87]
So, the javascript code in 'js/html5shiv.js' is full of Polish bible quotes, what's up with that?

**Comment by skandaI** [comment]
It's our protection against the newfags. All posted sentences are changed to quotes from the Bible. You can delete it.

**Comment by TheAdamGalloway** [comment]
Ah okay, it looked a bit malicious...

-Adam Galloway http://www.adamgalloway.tk/ (PGP KEY)
http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xE798AB9347B8CD1C

http://adamgalloway.tk/

**Comment by skandaI** [comment]
In our imageboard karachan.org we have much more malicious protections.

**Comment by TheAdamGalloway** [comment]
Excellent site! I hope to have similar protection when I release my
imageboard too!

-Adam Galloway http://www.adamgalloway.tk/ (PGP KEY)
http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xE798AB9347B8CD1C

http://adamgalloway.tk/

**Comment by TheAdamGalloway** [comment]
The reverse image search thing is nice, how did you do that?

-Adam Galloway http://www.adamgalloway.tk/ (PGP KEY)
http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xE798AB9347B8CD1C

http://adamgalloway.tk/
