### ISSUE TITLE
Adding an index page

### ISSUE THREAD

**Issue by nikillpop** [MitsubaBBS/Mitsuba#97]
how would i add an index page for Mitsuba so i don't have all the files showing?

**Comment by skandaI** [comment]
I don't understand your question. What files do you mean?

**Comment by nikillpop** [comment]
I mean the index page but i got it working but how do i add links to the index page aka the page that opens up when you type in the folder name

**Comment by skandaI** [comment]
![hht](https://user-images.githubusercontent.com/4047379/43607377-4e137bfe-969e-11e8-93f6-f2430ac21b56.png)
Manage board links.

**Comment by nikillpop** [comment]
it is just a box of text it is not a link and i rebuilt the stuff and i have the same settings as you
